#!/bin/bash

# 'files' 폴더로 이동
cd files

# a에서 z, A에서 Z까지 각 알파벳에 대해 반복
for letter in {a..z} {A..Z}; do

  # 해당 알파벳으로 시작하는 모든 .txt 파일을 해당 폴더로 이동
  # 파일이 존재할 경우에만 mv를 실행
  if ls "${letter}"*.txt 1> /dev/null 2>&1; then
    mv "${letter}"*.txt ../"${letter}"
  fi
done

# 원래 디렉토리로 돌아가기
cd ..